# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  autopairs = {
    pname = "autopairs";
    version = "59df87a84c80a357ca8d8fe86e451b93ac476ccc";
    src = fetchgit {
      url = "https://github.com/windwp/nvim-autopairs";
      rev = "59df87a84c80a357ca8d8fe86e451b93ac476ccc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-maSCppPEOFbkEfTYFKLq3M6Dg+fRjnqbCtsyWO9SILA=";
    };
    date = "2023-05-26";
  };
  bufdelete-nvim = {
    pname = "bufdelete-nvim";
    version = "ccfa2589fa68512770639839ab3850097fbbf4dc";
    src = fetchgit {
      url = "https://github.com/famiu/bufdelete.nvim";
      rev = "ccfa2589fa68512770639839ab3850097fbbf4dc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oqknglSi9leINjLCVgkEMAOiodwYjtiP43hZjCLxDbQ=";
    };
    date = "2023-05-28";
  };
  bufferline-lua = {
    pname = "bufferline-lua";
    version = "32d74d5d044f7cc89892d4781a83d55ee4ed552a";
    src = fetchgit {
      url = "https://github.com/akinsho/bufferline.nvim";
      rev = "32d74d5d044f7cc89892d4781a83d55ee4ed552a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WM8/dHqiEykuw0qEQtenM5Rcv/Jr3Jxj5vulC/IKfAE=";
    };
    date = "2023-05-21";
  };
  cinnamon = {
    pname = "cinnamon";
    version = "c406ffda3a0302f32c23b24ab756ea20467d6578";
    src = fetchgit {
      url = "https://github.com/declancm/cinnamon.nvim";
      rev = "c406ffda3a0302f32c23b24ab756ea20467d6578";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-JglXQhoPgN9sQ3yuv0+VQxmKMvoQTu5lbGLSRaQkytI=";
    };
    date = "2022-12-04";
  };
  cmp = {
    pname = "cmp";
    version = "b43bfaf3229d6b39d8baaa567b13c6be0623bf12";
    src = fetchgit {
      url = "https://github.com/hrsh7th/nvim-cmp";
      rev = "b43bfaf3229d6b39d8baaa567b13c6be0623bf12";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lspNjM7Q07sFfZBRslTcD2gz4ti/SBKYASA3rHlBsek=";
    };
    date = "2023-05-28";
  };
  cmp-buffer = {
    pname = "cmp-buffer";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchgit {
      url = "https://github.com/hrsh7th/cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dG4U7MtnXThoa/PD+qFtCt76MQ14V1wX8GMYcvxEnbM=";
    };
    date = "2022-08-10";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "0e6b2ed705ddcff9738ec4ea838141654f12eeef";
    src = fetchgit {
      url = "https://github.com/hrsh7th/cmp-nvim-lsp";
      rev = "0e6b2ed705ddcff9738ec4ea838141654f12eeef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-DxpcPTBlvVP88PDoTheLV2fC76EXDqS2UpM5mAfj/D4=";
    };
    date = "2023-02-07";
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchgit {
      url = "https://github.com/hrsh7th/cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    };
    date = "2022-10-03";
  };
  cmp-spell = {
    pname = "cmp-spell";
    version = "60584cb75e5e8bba5a0c9e4c3ab0791e0698bffa";
    src = fetchgit {
      url = "https://github.com/f3fora/cmp-spell";
      rev = "60584cb75e5e8bba5a0c9e4c3ab0791e0698bffa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-e6nHT+5xEXDFkWes89R85FdriPSP0fPiuoXwgBdH+9M=";
    };
    date = "2022-10-10";
  };
  cmp-treesitter = {
    pname = "cmp-treesitter";
    version = "c8e3a74b51597d69d240085a258636972ce98e15";
    src = fetchgit {
      url = "https://github.com/ray-x/cmp-treesitter";
      rev = "c8e3a74b51597d69d240085a258636972ce98e15";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-t1xEQn6NXcNG215ldm0ivKZdgaoGFwDiZUb8ROBeZHU=";
    };
    date = "2023-03-26";
  };
  cmp-vsnip = {
    pname = "cmp-vsnip";
    version = "989a8a73c44e926199bfd05fa7a516d51f2d2752";
    src = fetchgit {
      url = "https://github.com/hrsh7th/cmp-vsnip";
      rev = "989a8a73c44e926199bfd05fa7a516d51f2d2752";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2mkN03noOr5vBvRbSb35xZKorSH+8savQNZtgM9+QcM=";
    };
    date = "2022-11-22";
  };
  crates = {
    pname = "crates";
    version = "3648f8787656d7572740560331553abdaa8cb982";
    src = fetchgit {
      url = "https://github.com/saecki/crates.nvim";
      rev = "3648f8787656d7572740560331553abdaa8cb982";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qsVU22P9TC6wXghH/6VhQHmWcpQmRPUWVViPUSp3m6k=";
    };
    date = "2023-05-19";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "f868d82a36f7f7f5e110eb0a9659993984f59875";
    src = fetchgit {
      url = "https://github.com/lewis6991/gitsigns.nvim";
      rev = "f868d82a36f7f7f5e110eb0a9659993984f59875";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-R7ayrNWGJLKYAOg+P/On9i8nk7GQpY28N2mFb/yped0=";
    };
    date = "2023-05-25";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "ceaf730b13e332cd76600d9795722413c236c684";
    src = fetchgit {
      url = "https://github.com/lukas-reineke/indent-blankline.nvim";
      rev = "ceaf730b13e332cd76600d9795722413c236c684";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-eDfPgz5csbOHfI9FVXw1xGx+rTaoVzBTS8K1Cf618GA=";
    };
    date = "2023-05-26";
  };
  lspkind = {
    pname = "lspkind";
    version = "57610d5ab560c073c465d6faf0c19f200cb67e6e";
    src = fetchgit {
      url = "https://github.com/onsails/lspkind.nvim";
      rev = "57610d5ab560c073c465d6faf0c19f200cb67e6e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-S+qZm51hw/cRujIfHV/1x1fYyCKI4XQ0utSL8uy4l6I=";
    };
    date = "2023-05-05";
  };
  lualine = {
    pname = "lualine";
    version = "05d78e9fd0cdfb4545974a5aa14b1be95a86e9c9";
    src = fetchgit {
      url = "https://github.com/nvim-lualine/lualine.nvim";
      rev = "05d78e9fd0cdfb4545974a5aa14b1be95a86e9c9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ltHE8UIquGo07BSlFGM1l3wmTNN43i8kx6QY7Fj2CNo=";
    };
    date = "2023-05-04";
  };
  moonfly = {
    pname = "moonfly";
    version = "c4ae6851441edfe74f7fb46b0e8cc43f534b0aa5";
    src = fetchgit {
      url = "https://github.com/bluz71/vim-moonfly-colors";
      rev = "c4ae6851441edfe74f7fb46b0e8cc43f534b0aa5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-TiAnSIWi5fdzJ2VuuBaCwozaJ8ilKA3PoqhhxrK3Uok=";
    };
    date = "2023-05-21";
  };
  noice = {
    pname = "noice";
    version = "7e358170cea2314d9768b3f63616e8fad186195e";
    src = fetchgit {
      url = "https://github.com/folke/noice.nvim";
      rev = "7e358170cea2314d9768b3f63616e8fad186195e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FGxpAZ8srLxdXitR1lYyWtWgLi9+WInyJXF6d1GJynU=";
    };
    date = "2023-05-28";
  };
  nui = {
    pname = "nui";
    version = "2b2732528e4a79eb8542568bd51d25f710395bd6";
    src = fetchgit {
      url = "https://github.com/MunifTanjim/nui.nvim";
      rev = "2b2732528e4a79eb8542568bd51d25f710395bd6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-3wbIWsDjR1T8PrAQmiq2++BeGwMgCMx7Rb3qLb/zTy8=";
    };
    date = "2023-05-27";
  };
  null-ls = {
    pname = "null-ls";
    version = "4b055d84be42c90a7240785d3c83340d259d3d46";
    src = fetchgit {
      url = "https://github.com/jose-elias-alvarez/null-ls.nvim";
      rev = "4b055d84be42c90a7240785d3c83340d259d3d46";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-QaagLul44HFtqsPWJs919qkEzpQzDCnkeSwrRJEG4e4=";
    };
    date = "2023-05-28";
  };
  nvim-colorzier = {
    pname = "nvim-colorzier";
    version = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
    src = fetchgit {
      url = "https://github.com/norcalli/nvim-colorizer.lua";
      rev = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6YrnItxExL2C8pNIdLd+hXCjsB2MbZANwWkah6dreD8=";
    };
    date = "2020-06-11";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "465042c0f786992212284311ebb5da1f89479774";
    src = fetchgit {
      url = "https://github.com/neovim/nvim-lspconfig";
      rev = "465042c0f786992212284311ebb5da1f89479774";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-XADAxMQm7LfOQs7/WNtMbm3WSbIFPJ53VMvljHLPhmM=";
    };
    date = "2023-05-27";
  };
  plenary = {
    pname = "plenary";
    version = "52544825d6b8be677eb395983515ad5e30ae1f2e";
    src = fetchgit {
      url = "https://github.com/nvim-lua/plenary.nvim";
      rev = "52544825d6b8be677eb395983515ad5e30ae1f2e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-o83xyCwMhaJtEchbYtZMbIYERPHPZhk2wTPoz/t+RVA=";
    };
    date = "2023-05-24";
  };
  rust-tools = {
    pname = "rust-tools";
    version = "71d2cf67b5ed120a0e31b2c8adb210dd2834242f";
    src = fetchgit {
      url = "https://github.com/simrat39/rust-tools.nvim";
      rev = "71d2cf67b5ed120a0e31b2c8adb210dd2834242f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Cuk/vdoviB9ibt2rrkNRmNFy4S+6czhbExmIjTJRdZM=";
    };
    date = "2023-02-20";
  };
  telescope = {
    pname = "telescope";
    version = "6d3fbffe426794296a77bb0b37b6ae0f4f14f807";
    src = fetchgit {
      url = "https://github.com/nvim-telescope/telescope.nvim";
      rev = "6d3fbffe426794296a77bb0b37b6ae0f4f14f807";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FIAN3NQrD7PhrtCKnlrr//bZ259qcvGogL45nC8tLpw=";
    };
    date = "2023-05-25";
  };
  toggle-term = {
    pname = "toggle-term";
    version = "a44313fb28ed9bc9837c2b99dec1c6eed3a4f47f";
    src = fetchgit {
      url = "https://github.com/akinsho/toggleterm.nvim";
      rev = "a44313fb28ed9bc9837c2b99dec1c6eed3a4f47f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-mDxd6gxVuUVpbo6iIEzAyfyLNItn4dTbprRAG5PlECI=";
    };
    date = "2023-05-22";
  };
  tree-lua = {
    pname = "tree-lua";
    version = "e2a4c9d09d205ebe5f071264f43f73a0077c43a3";
    src = fetchgit {
      url = "https://github.com/nvim-tree/nvim-tree.lua";
      rev = "e2a4c9d09d205ebe5f071264f43f73a0077c43a3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-TZNibkRvpKBTxWwrziJMfVqbEOt4VGiuXjD/+bZhloE=";
    };
    date = "2023-05-27";
  };
  treesitter-context = {
    pname = "treesitter-context";
    version = "7cd5ac1c384b89e7e607238a936f13963f97ba32";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter-context";
      rev = "7cd5ac1c384b89e7e607238a936f13963f97ba32";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-kYPN02Ww/l0+79KPYfbWBSvTERmZ5lgwvGgbAlRpOtA=";
    };
    date = "2023-05-24";
  };
  vsnip = {
    pname = "vsnip";
    version = "7753ba9c10429c29d25abfd11b4c60b76718c438";
    src = fetchgit {
      url = "https://github.com/hrsh7th/vim-vsnip";
      rev = "7753ba9c10429c29d25abfd11b4c60b76718c438";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ehPnvGle7YrECn76YlSY/2V7Zeq56JGlmZPlwgz2FdE=";
    };
    date = "2023-03-12";
  };
  web-devicons = {
    pname = "web-devicons";
    version = "2a125024a137677930efcfdf720f205504c97268";
    src = fetchgit {
      url = "https://github.com/nvim-tree/nvim-web-devicons";
      rev = "2a125024a137677930efcfdf720f205504c97268";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-bryHxQZQ75wQXHLqYVh5zSkgLijdPvVAZPDYnv+JTkI=";
    };
    date = "2023-05-27";
  };
  which-key = {
    pname = "which-key";
    version = "e271c28118998c93a14d189af3395812a1aa646c";
    src = fetchgit {
      url = "https://github.com/folke/which-key.nvim";
      rev = "e271c28118998c93a14d189af3395812a1aa646c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wJo9XAUiru2WCeojL7aZuj0RDhkB5oClIpF/fGnXX6o=";
    };
    date = "2023-05-22";
  };
}
