# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  autopairs = {
    pname = "autopairs";
    version = "e755f366721bc9e189ddecd39554559045ac0a18";
    src = fetchgit {
      url = "https://github.com/windwp/nvim-autopairs";
      rev = "e755f366721bc9e189ddecd39554559045ac0a18";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ZVa5f5Evil6d60mWAca9txZyqOcKE6ZGygCggVOAKR8=";
    };
    date = "2023-03-07";
  };
  bufdelete-nvim = {
    pname = "bufdelete-nvim";
    version = "8933abc09df6c381d47dc271b1ee5d266541448e";
    src = fetchgit {
      url = "https://github.com/famiu/bufdelete.nvim";
      rev = "8933abc09df6c381d47dc271b1ee5d266541448e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-bh5PE0/QNK5et+E7cTz69wnZ9K09681nlQ+OI87ZU7g=";
    };
    date = "2023-02-17";
  };
  bufferline-lua = {
    pname = "bufferline-lua";
    version = "3677aceb9a72630b0613e56516c8f7151b86f95c";
    src = fetchgit {
      url = "https://github.com/akinsho/bufferline.nvim";
      rev = "3677aceb9a72630b0613e56516c8f7151b86f95c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-tuGitJQ2eXB9/SIHAyPrEVgy2n++GOlBOPLvFv3Ds4E=";
    };
    date = "2023-03-02";
  };
  cinnamon = {
    pname = "cinnamon";
    version = "c406ffda3a0302f32c23b24ab756ea20467d6578";
    src = fetchgit {
      url = "https://github.com/declancm/cinnamon.nvim";
      rev = "c406ffda3a0302f32c23b24ab756ea20467d6578";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-JglXQhoPgN9sQ3yuv0+VQxmKMvoQTu5lbGLSRaQkytI=";
    };
    date = "2022-12-04";
  };
  cmp = {
    pname = "cmp";
    version = "777450fd0ae289463a14481673e26246b5e38bf2";
    src = fetchgit {
      url = "https://github.com/hrsh7th/nvim-cmp";
      rev = "777450fd0ae289463a14481673e26246b5e38bf2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-CoHGIiZrhRAHZ/Er0JSQMapI7jwllNF5OysLlx2QEik=";
    };
    date = "2023-03-17";
  };
  cmp-buffer = {
    pname = "cmp-buffer";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchgit {
      url = "https://github.com/hrsh7th/cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dG4U7MtnXThoa/PD+qFtCt76MQ14V1wX8GMYcvxEnbM=";
    };
    date = "2022-08-10";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "0e6b2ed705ddcff9738ec4ea838141654f12eeef";
    src = fetchgit {
      url = "https://github.com/hrsh7th/cmp-nvim-lsp";
      rev = "0e6b2ed705ddcff9738ec4ea838141654f12eeef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-DxpcPTBlvVP88PDoTheLV2fC76EXDqS2UpM5mAfj/D4=";
    };
    date = "2023-02-07";
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchgit {
      url = "https://github.com/hrsh7th/cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    };
    date = "2022-10-03";
  };
  cmp-spell = {
    pname = "cmp-spell";
    version = "60584cb75e5e8bba5a0c9e4c3ab0791e0698bffa";
    src = fetchgit {
      url = "https://github.com/f3fora/cmp-spell";
      rev = "60584cb75e5e8bba5a0c9e4c3ab0791e0698bffa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-e6nHT+5xEXDFkWes89R85FdriPSP0fPiuoXwgBdH+9M=";
    };
    date = "2022-10-10";
  };
  cmp-treesitter = {
    pname = "cmp-treesitter";
    version = "b40178b780d547bcf131c684bc5fd41af17d05f2";
    src = fetchgit {
      url = "https://github.com/ray-x/cmp-treesitter";
      rev = "b40178b780d547bcf131c684bc5fd41af17d05f2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-+dOqV9QqN+s1no8vfL6DNeFBc2dYyduQqAH5zVwm3Rw=";
    };
    date = "2022-10-29";
  };
  cmp-vsnip = {
    pname = "cmp-vsnip";
    version = "989a8a73c44e926199bfd05fa7a516d51f2d2752";
    src = fetchgit {
      url = "https://github.com/hrsh7th/cmp-vsnip";
      rev = "989a8a73c44e926199bfd05fa7a516d51f2d2752";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2mkN03noOr5vBvRbSb35xZKorSH+8savQNZtgM9+QcM=";
    };
    date = "2022-11-22";
  };
  crates = {
    pname = "crates";
    version = "aa94d3844d6a12b1a8bf73c8a242ff2f540fb749";
    src = fetchgit {
      url = "https://github.com/saecki/crates.nvim";
      rev = "aa94d3844d6a12b1a8bf73c8a242ff2f540fb749";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-iPRdzdWawz7WKV2jK+JJ/JOqSCrec21MV7vUqmS5aaY=";
    };
    date = "2023-03-12";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "b1f9cf7c5c5639c006c937fc1819e09f358210fc";
    src = fetchgit {
      url = "https://github.com/lewis6991/gitsigns.nvim";
      rev = "b1f9cf7c5c5639c006c937fc1819e09f358210fc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-kRa1dO49Z1fYqaFvUmvHEnYXdYvVp5iEEswkuNl9yQA=";
    };
    date = "2023-03-06";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "018bd04d80c9a73d399c1061fa0c3b14a7614399";
    src = fetchgit {
      url = "https://github.com/lukas-reineke/indent-blankline.nvim";
      rev = "018bd04d80c9a73d399c1061fa0c3b14a7614399";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dBm0vnza+fBYxlgUDR1/57GZ+kd7CUVgkQIcZEFWl9k=";
    };
    date = "2023-02-20";
  };
  lspkind = {
    pname = "lspkind";
    version = "c68b3a003483cf382428a43035079f78474cd11e";
    src = fetchgit {
      url = "https://github.com/onsails/lspkind.nvim";
      rev = "c68b3a003483cf382428a43035079f78474cd11e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WwUQ+O2rIfD4yl0GFx70GsZc9nnhS7b2KWfNdaXCLmM=";
    };
    date = "2022-09-22";
  };
  lualine = {
    pname = "lualine";
    version = "e99d733e0213ceb8f548ae6551b04ae32e590c80";
    src = fetchgit {
      url = "https://github.com/nvim-lualine/lualine.nvim";
      rev = "e99d733e0213ceb8f548ae6551b04ae32e590c80";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-mItWWRqWj9a/JaW8sccnGBijBsvvnh/b4q/S60UwYwc=";
    };
    date = "2023-02-14";
  };
  moonfly = {
    pname = "moonfly";
    version = "b2000bf399f9de69d55ce9aafbcbd598142dd141";
    src = fetchgit {
      url = "https://github.com/bluz71/vim-moonfly-colors";
      rev = "b2000bf399f9de69d55ce9aafbcbd598142dd141";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-T4FH/ZMezCbwgz00whP25H20gWzo67zcBh9pv6FcFIw=";
    };
    date = "2023-03-10";
  };
  noice = {
    pname = "noice";
    version = "92b058ad183fccd3b970f03ae49094596a6c735b";
    src = fetchgit {
      url = "https://github.com/folke/noice.nvim";
      rev = "92b058ad183fccd3b970f03ae49094596a6c735b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FtW44trf/U4G8ORi5FHBRCR8P8hTBE07wW6OWk6h1kw=";
    };
    date = "2023-03-19";
  };
  nui = {
    pname = "nui";
    version = "0dc148c6ec06577fcf06cbab3b7dac96d48ba6be";
    src = fetchgit {
      url = "https://github.com/MunifTanjim/nui.nvim";
      rev = "0dc148c6ec06577fcf06cbab3b7dac96d48ba6be";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xHpNGJ8ikTMiWHAtqaZg5IVKSngH/k0LN7WaOHl2iz8=";
    };
    date = "2023-02-28";
  };
  null-ls = {
    pname = "null-ls";
    version = "456a983ce9843123e51b955f50925077ca7207d5";
    src = fetchgit {
      url = "https://github.com/jose-elias-alvarez/null-ls.nvim";
      rev = "456a983ce9843123e51b955f50925077ca7207d5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SILAY9kWphXflElejCDkoFv3qxJrjD29Diipbfp0dfA=";
    };
    date = "2023-03-17";
  };
  nvim-colorzier = {
    pname = "nvim-colorzier";
    version = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
    src = fetchgit {
      url = "https://github.com/norcalli/nvim-colorizer.lua";
      rev = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6YrnItxExL2C8pNIdLd+hXCjsB2MbZANwWkah6dreD8=";
    };
    date = "2020-06-11";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "5a871409199d585b52b69952532e3fb435e64566";
    src = fetchgit {
      url = "https://github.com/neovim/nvim-lspconfig";
      rev = "5a871409199d585b52b69952532e3fb435e64566";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wGcqUcUpw3mzhOhDp1J3FqSGjzDt5nTSWvDtpCsAuY0=";
    };
    date = "2023-03-18";
  };
  plenary = {
    pname = "plenary";
    version = "253d34830709d690f013daf2853a9d21ad7accab";
    src = fetchgit {
      url = "https://github.com/nvim-lua/plenary.nvim";
      rev = "253d34830709d690f013daf2853a9d21ad7accab";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-z5JHuQcF1EvySnRBywl6EOrp8aRO0nd2dnkXJg2ge58=";
    };
    date = "2023-02-19";
  };
  rust-tools = {
    pname = "rust-tools";
    version = "71d2cf67b5ed120a0e31b2c8adb210dd2834242f";
    src = fetchgit {
      url = "https://github.com/simrat39/rust-tools.nvim";
      rev = "71d2cf67b5ed120a0e31b2c8adb210dd2834242f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Cuk/vdoviB9ibt2rrkNRmNFy4S+6czhbExmIjTJRdZM=";
    };
    date = "2023-02-20";
  };
  telescope = {
    pname = "telescope";
    version = "a3f17d3baf70df58b9d3544ea30abe52a7a832c2";
    src = fetchgit {
      url = "https://github.com/nvim-telescope/telescope.nvim";
      rev = "a3f17d3baf70df58b9d3544ea30abe52a7a832c2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-QmyVJ/LZFtb/qqD5Q5fHsqAGgqaOT9XkVoLyOcqM14w=";
    };
    date = "2023-02-26";
  };
  toggle-term = {
    pname = "toggle-term";
    version = "9a595ba699837c4333c4296634feed320f084df2";
    src = fetchgit {
      url = "https://github.com/akinsho/toggleterm.nvim";
      rev = "9a595ba699837c4333c4296634feed320f084df2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-8WPLJ046KxGRAk6q6qXLKDFo4lV+Ek6Zt9TXnFW3mJQ=";
    };
    date = "2023-03-16";
  };
  tree-lua = {
    pname = "tree-lua";
    version = "1d79a64a88af47ddbb55f4805ab537d11d5b908e";
    src = fetchgit {
      url = "https://github.com/nvim-tree/nvim-tree.lua";
      rev = "1d79a64a88af47ddbb55f4805ab537d11d5b908e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-u9ZLBL4FY/bkvl4+ofKifyEHM9+KhqeYovhr9VQYG7c=";
    };
    date = "2023-03-14";
  };
  treesitter-context = {
    pname = "treesitter-context";
    version = "c1fa59698850cafa4cae686e652d1512a01dcf3c";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter-context";
      rev = "c1fa59698850cafa4cae686e652d1512a01dcf3c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-DAApzkdBrEutXDU2pI1tLPlCbD98UpokJ0KjeQpnv74=";
    };
    date = "2023-03-19";
  };
  vsnip = {
    pname = "vsnip";
    version = "7753ba9c10429c29d25abfd11b4c60b76718c438";
    src = fetchgit {
      url = "https://github.com/hrsh7th/vim-vsnip";
      rev = "7753ba9c10429c29d25abfd11b4c60b76718c438";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ehPnvGle7YrECn76YlSY/2V7Zeq56JGlmZPlwgz2FdE=";
    };
    date = "2023-03-12";
  };
  web-devicons = {
    pname = "web-devicons";
    version = "585dbc29315ca60be67d18ae6175771c3fb6791e";
    src = fetchgit {
      url = "https://github.com/nvim-tree/nvim-web-devicons";
      rev = "585dbc29315ca60be67d18ae6175771c3fb6791e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-7GiM/A6Tf9zxqAbv/o+3a+8mw2M6SOtyLfkzmwu88ro=";
    };
    date = "2023-03-16";
  };
  which-key = {
    pname = "which-key";
    version = "d1afcd48f309af58fdb43adc4581bf4b5684768b";
    src = fetchgit {
      url = "https://github.com/folke/which-key.nvim";
      rev = "d1afcd48f309af58fdb43adc4581bf4b5684768b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-AIvUyyv8rOFP4B5REl+TslU7XFUzP8jaAy+sdvw4Izo=";
    };
    date = "2023-03-19";
  };
}
