name: update_deps

on:
  workflow_dispatch: #allow manual triggering
  schedule:
      - cron: "0 0 * * 0"
jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v31
      - name: setup git
        run: | 
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - uses: cachix/cachix-action@v16
        with:
          name: nvim-flake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - id: flake
        name: flake
        run: |
          MESSAGE="
          flake input updates:
          $(nix flake update --no-warn-dirty 2>&1 | { grep -v 'unpacking.*' || true; } | sed '1d')"

          if [ -n "$(git diff-files 2>&1)" ]; then
            git add -A
            {
              echo "message<<EOF"
              echo "$MESSAGE"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          fi

      - id: npins
        name: npins
        run: |
          MESSAGE="
          npins updates:
            $(nix run nixpkgs#npins -- update -f 2>&1 | { grep '.*Changes:$\|.*url:.*' || true; })"

          if [ -n "$(git diff-files 2>&1)" ]; then
            git add -A
            {
              echo "message<<EOF"
              echo "$MESSAGE"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          fi

      - id: nix-update
        name: nix-update
        run: |
          FILE="$(mktemp)"
          nix run nixpkgs#nix-update -- --write-commit-message "$FILE" -F blink-cmp --version=branch
          MESSAGE="
          nix-update updates:
          $(cat "$FILE" | sed '1!d')"

          if [ -n "$(git diff-files 2>&1)" ]; then
            git add -A
            {
              echo "message<<EOF"
              echo "$MESSAGE"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push
        run: |
          MESSAGE="
          ${{ steps.flake.outputs.message }}
          ${{ steps.npins.outputs.message }}
          ${{ steps.nix-update.outputs.message }}
          "
          if [[ "$MESSAGE" =~ ^[[:space:]]*$ ]]; then
            exit 0
          fi

          git commit -m "CI update $(date -I)" -m "$MESSAGE"
          git push origin 'HEAD:${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
