name: update_deps

on:
  workflow_dispatch: #allow manual triggering
  schedule:
      - cron: "0 0 * * 0"
jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v31
      - name: setup git
        run: | 
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - uses: cachix/cachix-action@v16
        with:
          name: nvim-flake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: update
        run: |
          MESSAGE=""

          nix flake update --no-warn-dirty --commit-lock-file

          if git rev-parse -q HEAD^; then

            MESSAGE="$(git -P log --pretty=format:"%s%n%b" -1)"

            git reset --soft HEAD^
          fi

          NPINS=$(nix run nixpkgs#npins -- update -f | grep -E '[^\(no changes\)]*url.*')

          if [ -n "$(git status --porcelain=v1 2>/dev/null)" ]; then
            MESSAGE="$MESSAGE

          npins url updates:
          $NPINS"
          fi

          nix run nixpkgs#nix-update -- -F blink-cmp --version=branch --commit

          if git rev-parse -q HEAD^; then

            nix build .#blink-cmp

            MESSAGE="$MESSAGE

            $(git -P log --pretty=format:"%s%n%b" -1)"

            git reset --soft HEAD^
          fi

          if [ -z "$MESSAGE" ]; then
            exit 0
          fi
          
          git add -A

          git commit -m "CI update $(date -I)" -m "$MESSAGE"

          git push origin HEAD:${{ github.ref_name }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
